# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 521)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 521))
        self.label.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            color: white;\n"
"            background-color: green;  /* 绿色背景 */\n"
"            border: 2px solid white;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            background-image: url(\"D:/大三下/企业实训/第一周_图像识别api调用/project1/data/动物0.JPG\");\n"
"            background-position: center;\n"
"            background-repeat: no-repeat;\n"
"            background-size: cover;  /* 调整背景图片的大小，使其覆盖标签 */")
        self.label.setText("")
        self.label.setObjectName("label")
        self.animal_video = QtWidgets.QLabel(Dialog)
        self.animal_video.setGeometry(QtCore.QRect(190, 200, 531, 301))
        self.animal_video.setText("")
        self.animal_video.setObjectName("animal_video")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 91, 41))
        self.label_2.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_2.setObjectName("label_2")
        self.animal1 = QtWidgets.QLabel(Dialog)
        self.animal1.setGeometry(QtCore.QRect(90, 20, 91, 41))
        self.animal1.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal1.setObjectName("animal1")
        self.probability1 = QtWidgets.QLabel(Dialog)
        self.probability1.setGeometry(QtCore.QRect(270, 20, 91, 41))
        self.probability1.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability1.setObjectName("probability1")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(180, 80, 91, 41))
        self.label_5.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_5.setObjectName("label_5")
        self.animal2 = QtWidgets.QLabel(Dialog)
        self.animal2.setGeometry(QtCore.QRect(90, 80, 91, 41))
        self.animal2.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal2.setObjectName("animal2")
        self.probability2 = QtWidgets.QLabel(Dialog)
        self.probability2.setGeometry(QtCore.QRect(270, 80, 91, 41))
        self.probability2.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability2.setObjectName("probability2")
        self.animal3 = QtWidgets.QLabel(Dialog)
        self.animal3.setGeometry(QtCore.QRect(90, 140, 91, 41))
        self.animal3.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal3.setObjectName("animal3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(180, 140, 91, 41))
        self.label_9.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_9.setObjectName("label_9")
        self.probability3 = QtWidgets.QLabel(Dialog)
        self.probability3.setGeometry(QtCore.QRect(270, 140, 91, 41))
        self.probability3.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability3.setObjectName("probability3")
        self.animal5 = QtWidgets.QLabel(Dialog)
        self.animal5.setGeometry(QtCore.QRect(570, 80, 91, 41))
        self.animal5.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal5.setObjectName("animal5")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(660, 80, 91, 41))
        self.label_12.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_12.setObjectName("label_12")
        self.probability5 = QtWidgets.QLabel(Dialog)
        self.probability5.setGeometry(QtCore.QRect(750, 80, 91, 41))
        self.probability5.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability5.setObjectName("probability5")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(660, 20, 91, 41))
        self.label_14.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_14.setObjectName("label_14")
        self.probability6 = QtWidgets.QLabel(Dialog)
        self.probability6.setGeometry(QtCore.QRect(750, 140, 91, 41))
        self.probability6.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability6.setObjectName("probability6")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(660, 140, 91, 41))
        self.label_16.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.label_16.setObjectName("label_16")
        self.animal4 = QtWidgets.QLabel(Dialog)
        self.animal4.setGeometry(QtCore.QRect(570, 20, 91, 41))
        self.animal4.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal4.setObjectName("animal4")
        self.animal6 = QtWidgets.QLabel(Dialog)
        self.animal6.setGeometry(QtCore.QRect(570, 140, 91, 41))
        self.animal6.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.animal6.setObjectName("animal6")
        self.probability4 = QtWidgets.QLabel(Dialog)
        self.probability4.setGeometry(QtCore.QRect(750, 20, 91, 41))
        self.probability4.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            color: yellow;  /* 黄色文字 */\n"
"            background-color: #000000;  /* 黑色背景 */\n"
"            border: 2px solid #FFD700;  /* 金黄色边框 */\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.5);  /* 添加阴影效果 */")
        self.probability4.setObjectName("probability4")
        self.label.raise_()
        self.label_2.raise_()
        self.animal1.raise_()
        self.probability1.raise_()
        self.label_5.raise_()
        self.animal2.raise_()
        self.probability2.raise_()
        self.animal3.raise_()
        self.label_9.raise_()
        self.probability3.raise_()
        self.animal5.raise_()
        self.label_12.raise_()
        self.probability5.raise_()
        self.label_14.raise_()
        self.probability6.raise_()
        self.label_16.raise_()
        self.animal4.raise_()
        self.animal6.raise_()
        self.probability4.raise_()
        self.animal_video.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "可能性为："))
        self.animal1.setText(_translate("Dialog", "？"))
        self.probability1.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "可能性为："))
        self.animal2.setText(_translate("Dialog", "？"))
        self.probability2.setText(_translate("Dialog", "0"))
        self.animal3.setText(_translate("Dialog", "？"))
        self.label_9.setText(_translate("Dialog", "可能性为："))
        self.probability3.setText(_translate("Dialog", "0"))
        self.animal5.setText(_translate("Dialog", "？"))
        self.label_12.setText(_translate("Dialog", "可能性为："))
        self.probability5.setText(_translate("Dialog", "0"))
        self.label_14.setText(_translate("Dialog", "可能性为："))
        self.probability6.setText(_translate("Dialog", "0"))
        self.label_16.setText(_translate("Dialog", "可能性为："))
        self.animal4.setText(_translate("Dialog", "？"))
        self.animal6.setText(_translate("Dialog", "？"))
        self.probability4.setText(_translate("Dialog", "0"))
