# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'land_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(932, 521)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 521))
        self.label.setStyleSheet("            font-family: \"Arial\";\n"
"            font-size: 24px;\n"
"            font-weight: bold;\n"
"            color: white;\n"
"            background-color: green;  /* 绿色背景 */\n"
"            border: 2px solid white;\n"
"            border-radius: 10px;\n"
"            padding: 10px;\n"
"            text-align: center;\n"
"            background-image: url(\"D:/大三下/企业实训/第一周_图像识别api调用/project1/data/地标0.JPG\");\n"
"            background-position: center;\n"
"            background-repeat: no-repeat;\n"
"            background-size: cover;  /* 调整背景图片的大小，使其覆盖标签 */")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 161, 51))
        self.label_2.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #2F4F4F;  /* 深灰色背景 */\n"
"    border: 2px solid #2F4F4F;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    text-align: center;  /* 居中对齐 */")
        self.label_2.setObjectName("label_2")
        self.land_video = QtWidgets.QLabel(Dialog)
        self.land_video.setGeometry(QtCore.QRect(200, 170, 531, 301))
        self.land_video.setText("")
        self.land_video.setObjectName("land_video")
        self.land_name = QtWidgets.QLabel(Dialog)
        self.land_name.setGeometry(QtCore.QRect(270, 60, 161, 51))
        self.land_name.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #2F4F4F;  /* 深灰色背景 */\n"
"    border: 2px solid #2F4F4F;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    text-align: center;  /* 居中对齐 */")
        self.land_name.setObjectName("land_name")
        self.label.raise_()
        self.label_2.raise_()
        self.land_name.raise_()
        self.land_video.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "地标识别为："))
        self.land_name.setText(_translate("Dialog", "?"))
