# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(929, 519)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 521))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 371, 51))
        self.label_2.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: green;\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    text-align: center;")
        self.label_2.setObjectName("label_2")
        self.login_commit = QtWidgets.QPushButton(Dialog)
        self.login_commit.setGeometry(QtCore.QRect(400, 330, 131, 51))
        self.login_commit.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;")
        self.login_commit.setObjectName("login_commit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 200, 91, 51))
        self.label_3.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 140, 151, 51))
        self.label_4.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 280, 91, 51))
        self.label_5.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.cin_account = QtWidgets.QLineEdit(Dialog)
        self.cin_account.setGeometry(QtCore.QRect(380, 200, 231, 51))
        self.cin_account.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"")
        self.cin_account.setObjectName("cin_account")
        self.cin_password = QtWidgets.QLineEdit(Dialog)
        self.cin_password.setGeometry(QtCore.QRect(380, 280, 231, 51))
        self.cin_password.setStyleSheet("    font-family: \"Arial\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: #4CAF50;  /* 绿色背景 */\n"
"    border: 2px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"")
        self.cin_password.setObjectName("cin_password")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(360, 400, 281, 31))
        self.label_6.setStyleSheet("    \n"
"    color: white;\n"
"font: 63 italic 12pt \"Cascadia Code SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(340, 430, 331, 41))
        self.label_7.setStyleSheet("    \n"
"    color: white;\n"
"font: 63 italic 12pt \"Cascadia Code SemiBold\";")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "穷游世界——您身边的安全管家"))
        self.login_commit.setText(_translate("Dialog", "确认登录"))
        self.label_3.setText(_translate("Dialog", "账号："))
        self.label_4.setText(_translate("Dialog", "请您登录账号："))
        self.label_5.setText(_translate("Dialog", "密码："))
        self.label_6.setText(_translate("Dialog", ">--必须是11位数字--<"))
        self.label_7.setText(_translate("Dialog", ">--必须是数字和字母组合--<"))
